### PR TITLE
Renaming and switch openfisca branch to master

### PR DESCRIPTION
**Pull request by adrienpacifico**

### CODE REVIEW

**Comment by benjello** [comment]
Does this PR closes #110 ?

**Comment by adrienpacifico** [comment]
I think it does, I do not guarantee that all [#379](https://github.com/openfisca/openfisca-france/pull/379#event-530014330) changes are taken into account.

**Comment by benjello** [comment]
Let's check them then: 

- [ ] Rename chonet to chomage_net
- [ ] Rename chobrut to chomage_brut
- [ ] Rename cho to chomage_imposable
- [ ] Rename rstbrut to retraite_brute
- [ ] Rename rstnet to retraite_nette
- [ ] Rename rst to retraite_imposable
- [ ] Rename etu to etudiant
- [ ] Rename rto to retraite_titre_onereux

**Comment by adrienpacifico** [comment]
rto and etu looks ok from a quick Atom search over my openfisca folder.

**Comment by benjello** [comment]
The problems may come from openfisca-france-data ...

**Comment by adrienpacifico** [comment]
I don't understand ? My openfisca folders contains all openfisca subproject, thus of-data.

**Comment by benjello** [comment]
Look at your input data frame. You may have a rto variable since it comes
from fiscal data. Look also at the logs when importing data in simulation i
had strange warnings when I looked at it this morning.

Le mer. 17 févr. 2016 12:25, adrienpacifico <notifications@github.com> a
écrit :

> I don't understand ? My openfisca folders contains all openfisca
> subproject, thus of-data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfisca/openfisca-france-data/pull/111#issuecomment-185160365>
> .
>
-- 
Mahdi Ben Jelloul

**Comment by adrienpacifico** [comment]
Gotcha, I'll do it.

**Comment by benjello** [comment]
Merged c31c4762fdb0ef8d10dfdcae4db024a3e7cd0e2c by hand on openfisca/openfisca-france-data/migration

**Comment by benjello** [comment]
closes #110

**Pull request closed without merging**
